### ISSUE TITLE
response too slow

### ISSUE THREAD

**Issue by Singein** [jczic/MicroWebSrv#42]
thanks for sharing this amazing project!
the average of http-responsing time is too slow, about 3 seconds.
Is there a way to optimize?

**Comment by jczic** [comment]
What's your platform and how memory SDRAM have you ?

**Comment by Singein** [comment]
esp32 , about 128k RAM

**Comment by jczic** [comment]
There are many memory allocation in the web server, 128k is can be just if you have microwebsrv (websockets? pyhtml?) + another code around.

Do you use the threaded mode or the blocking mode? 3 seconds, it's slow yes...

You can also adjust threads stack size of your micro-controller.

However, this is not due to the DNS resolving?

**Comment by Singein** [comment]
hi，buddy, I just bought a new esp32 chip with psram. And I'm going to test it tomorrow.

**Comment by jczic** [comment]
Ok
