### ISSUE TITLE
SendText

### ISSUE THREAD

**Issue by gpspelle** [jczic/MicroWebSrv#70]
Hi, 

After reading this incredible Library, I am not sure yet about the send message process. As far as I understood, the example that you gave in your main.py file, you send a reply whenever you have received a message. But how should I do to send a message even I didn't get a message in the first place?

Thanks!

**Comment by jczic** [comment]
Hello @gpspelle,

Could you use MicroWebSrv2 lib instead of MicroWebSrv 👍 
(https://github.com/jczic/MicroWebSrv2)

You can check the `OnWSChatTextMsg()` function in `main.py` who is used to send msg to all WebSockets connections (for the chat example) registered in `_chatWebSockets` list.
You can first register websockets object (connections) in an array and after, send messages when you want (by a timer or any event).
It's ok for you?

**Comment by gpspelle** [comment]
Yeah, I'll try to use it, but I don't know if this will solve my problem in the end.

**Comment by jczic** [comment]
And what's your problem exactly?

**Comment by Kiri-fr** [comment]
Hi Gabriel, I had the same issue.
What you could do is: 

def _acceptWebSocketCallback(webSocket, httpClient) :
    print("WS ACCEPT")
    global WS
    WS = webSocket   # Save socket access point for external use
    webSocket.RecvTextCallback = _recvTextCallback
    webSocket.RecvBinaryCallback = _recvBinaryCallback
    webSocket.ClosedCallback = _closedCallback


WS.SendText("Hi")

This code was proposed by Marc Fiot
